# Generated by Django 5.2.6 on 2025-09-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditoria',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='peso_requisicao',
            field=models.CharField(choices=[('P1', 'PESO 01'), ('P2', 'PESO 02'), ('P3', 'PESO 03')], max_length=2, verbose_name='Peso da Requisição'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='status_requisicao',
            field=models.CharField(choices=[('ESPERA', 'Em Espera'), ('PROCESSAMENTO', 'Em Processamento'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], max_length=20, verbose_name='Status da Requisição'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='tipo_documento',
            field=models.CharField(choices=[('IPL', 'IPL'), ('BOP', 'BOP'), ('OF', 'OF')], max_length=4, verbose_name='Tipo de Documento'),
        ),
    ]
