# Generated by Django 5.2.6 on 2025-09-16 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0002_remove_auditoria_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='data_entrega_perito',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Entrega ao Perito'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='perito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerenciamento.perito', verbose_name='Perito'),
        ),
    ]
