# Generated by Django 5.2.6 on 2025-09-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0003_alter_protocolo_data_entrega_perito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='numero_documento',
            field=models.CharField(default='PENDENTE', max_length=20, verbose_name='Número do Documento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='numero_caso',
            field=models.CharField(max_length=10, unique=True, verbose_name='Número do Caso'),
        ),
    ]
