# Generated by Django 5.2.6 on 2025-09-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0004_requisicao_numero_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='numero_caso',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número do Caso'),
        ),
    ]
