# Generated by Django 5.2.6 on 2025-09-16 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0005_alter_requisicao_numero_caso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipamento',
            old_name='quant_equipamente',
            new_name='quant_equipamento',
        ),
    ]
