# Generated by Django 5.2.6 on 2025-09-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0006_rename_quant_equipamente_equipamento_quant_equipamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armazenamento',
            name='deposito',
            field=models.CharField(choices=[('D1', 'Depósito 1'), ('D2', 'Depósito 2'), ('D3', 'Depósito 3')], max_length=50, verbose_name='Depósito'),
        ),
    ]
