# Generated by Django 5.2.6 on 2025-09-16 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=50)),
                ('numero_documento', models.CharField(max_length=100)),
                ('numero_requisicao', models.CharField(max_length=100, unique=True)),
                ('data_requisicao', models.DateField()),
                ('solicitante', models.CharField(max_length=200)),
                ('unidade_solicitante', models.CharField(max_length=200)),
                ('tipo_exame', models.CharField(max_length=100)),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('numero_protocolo', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_caso', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel_prioridade', models.CharField(max_length=50)),
                ('status', models.CharField(default='Pendente', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_equipamento', models.CharField(max_length=100)),
                ('outros_tipo_equipamento', models.CharField(blank=True, max_length=100, null=True)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('local_armazenamento', models.CharField(max_length=100)),
                ('prateleira', models.CharField(blank=True, max_length=100, null=True)),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='requisicoes.requisicao')),
            ],
        ),
    ]
