# Generated by Django 5.2.6 on 2025-09-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='prateleira',
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='numero_protocolo',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
