# Generated by Django 5.2.6 on 2025-09-19 01:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicoes', '0002_remove_material_prateleira_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='prateleira',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='O campo prateleira só pode conter letras, números, espaços e hifens.', regex='^[a-zA-Z0-9\\s-]*$')]),
        ),
    ]
