name: Pipeline de CI do Django

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install Django==5.0.6 djangorestframework djangorestframework-simplejwt corsheaders

      - name: Rodar Migrações do Django
        run: |
          cd backend
          python manage.py makemigrations
          python manage.py migrate

      - name: Rodar Testes do Django
        run: |
          cd backend
          python manage.py test
