name: Pipeline de CI do Django

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: django_user
          POSTGRES_PASSWORD: django_password
          POSTGRES_DB: django_db_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint psycopg2-binary  # Instala Pylint e o driver do DB

      - name: Configurar Variáveis de Ambiente do Django
        run: |
          echo "PGHOST=localhost" >> $GITHUB_ENV
          echo "PGPORT=5432" >> $GITHUB_ENV
          echo "PGUSER=django_user" >> $GITHUB_ENV
          echo "PGPASSWORD=django_password" >> $GITHUB_ENV
          echo "PGDATABASE=django_db_test" >> $GITHUB_ENV
          echo "SECRET_KEY=sua-chave-secreta-aqui" >> $GITHUB_ENV
          echo "DEBUG=True" >> $GITHUB_ENV

      - name: Rodar Análise de Código com Pylint
        run: cd backend && pylint gerenciamento --fail-under=7.0

      - name: Rodar Migrações do Django
        run: |
          cd backend
          python manage.py migrate

      - name: Rodar Testes do Django
        run: |
          cd backend
          python manage.py test
