name: Django CI

on:
  push:
    branches:
      - 'backend-cadastro-de-requisicao'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Django djangorestframework

      - name: Run migrations
        run: |
          python backend/manage.py migrate

      - name: Run tests
        run: |
          python backend/manage.py test requisicoes
