name: Django CI

on:
  push:
    branches:
      - 'main' # A pipeline será executada toda vez que houver um push para a branch 'main'.

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          python backend/manage.py migrate

      - name: Run tests
        run: |
          # Navega para a pasta do backend antes de rodar os testes
          cd backend
          python manage.py test